(define (problem task)
(:domain small-quadrotor-world)
(:objects
    drone - quadrotor
    location00 location01 location02 location03 location10 location11 location12 location13 location20 location21 location22 location23 location30 location31 location32 location33 - location
)
(:init
    (checked location00)
    (checked location33)

    (unchecked location01)
    (unchecked location02)
    (unchecked location03)
    (unchecked location10)
    (unchecked location11)
    (unchecked location12)
    (unchecked location13)
    (unchecked location20)
    (unchecked location21)
    (unchecked location22)
    (unchecked location23)
    (unchecked location30)
    (unchecked location31)
    (unchecked location32)

    (pictured location00)
    (pictured location33)

    (unpictured location01)
    (unpictured location02)
    (unpictured location03)
    (unpictured location10)
    (unpictured location11)
    (unpictured location12)
    (unpictured location13)
    (unpictured location20)
    (unpictured location21)
    (unpictured location22)
    (unpictured location23)
    (unpictured location30)
    (unpictured location31)
    (unpictured location32)

    (locationadjust location00 location01)
    (locationadjust location00 location10)
    (locationadjust location00 location11)
    (locationadjust location01 location00)
    (locationadjust location01 location10)
    (locationadjust location01 location11)
    (locationadjust location01 location12)
    (locationadjust location01 location02)
    (locationadjust location02 location01)
    (locationadjust location02 location11)
    (locationadjust location02 location12)
    (locationadjust location02 location13)
    (locationadjust location02 location03)
    (locationadjust location03 location02)
    (locationadjust location03 location12)
    (locationadjust location03 location13)
    (locationadjust location10 location00)
    (locationadjust location10 location01)
    (locationadjust location10 location11)
    (locationadjust location10 location21)
    (locationadjust location10 location20)
    (locationadjust location11 location00)
    (locationadjust location11 location01)
    (locationadjust location11 location02)
    (locationadjust location11 location12)
    (locationadjust location11 location22)
    (locationadjust location11 location21)
    (locationadjust location11 location20)
    (locationadjust location11 location10)
    (locationadjust location12 location11)
    (locationadjust location12 location01)
    (locationadjust location12 location02)
    (locationadjust location12 location03)
    (locationadjust location12 location22)
    (locationadjust location12 location21)
    (locationadjust location12 location23)
    (locationadjust location12 location13)
    (locationadjust location13 location23)
    (locationadjust location13 location22)
    (locationadjust location13 location12)
    (locationadjust location13 location02)
    (locationadjust location13 location03)
    (locationadjust location20 location30)
    (locationadjust location20 location31)
    (locationadjust location20 location21)
    (locationadjust location20 location11)
    (locationadjust location20 location10)
    (locationadjust location21 location30)
    (locationadjust location21 location31)
    (locationadjust location21 location32)
    (locationadjust location21 location22)
    (locationadjust location21 location12)
    (locationadjust location21 location11)
    (locationadjust location21 location10)
    (locationadjust location21 location20)
    (locationadjust location22 location31)
    (locationadjust location22 location32)
    (locationadjust location22 location33)
    (locationadjust location22 location23)
    (locationadjust location22 location13)
    (locationadjust location22 location12)
    (locationadjust location22 location11)
    (locationadjust location22 location21)
    (locationadjust location23 location33)
    (locationadjust location23 location32)
    (locationadjust location23 location22)
    (locationadjust location23 location12)
    (locationadjust location23 location13)
    (locationadjust location30 location31)
    (locationadjust location30 location21)
    (locationadjust location30 location20)
    (locationadjust location31 location30)
    (locationadjust location31 location20)
    (locationadjust location31 location21)
    (locationadjust location31 location22)
    (locationadjust location31 location32)
    (locationadjust location32 location31)
    (locationadjust location32 location21)
    (locationadjust location32 location22)
    (locationadjust location32 location23)
    (locationadjust location32 location33)
    (locationadjust location33 location32)
    (locationadjust location33 location22)
    (locationadjust location33 location13)

    (at_d drone location00)

    (containobst location12)

    (notcontainobst location00)
    (notcontainobst location01)
    (notcontainobst location02)
    (notcontainobst location03)
    (notcontainobst location10)
    (notcontainobst location11)
    (notcontainobst location13)
    (notcontainobst location20)
    (notcontainobst location21)
    (notcontainobst location22)
    (notcontainobst location23)
    (notcontainobst location30)
    (notcontainobst location31)
    (notcontainobst location32)
    (notcontainobst location33)

    (heighthigh drone)


)
(:goal (and
    (pictured location00)
    (pictured location01)
    (pictured location02)
    (pictured location03)
    (pictured location10)
    (pictured location11)
    (pictured location13)
    (pictured location20)
    (pictured location21)
    (pictured location22)
    (pictured location23)
    (pictured location30)
    (pictured location31)
    (pictured location32)
    (pictured location33)
    (checked location00)
    (checked location01)
    (checked location02)
    (checked location03)
    (checked location10)
    (checked location11)
    (checked location13)
    (checked location20)
    (checked location21)
    (checked location22)
    (checked location23)
    (checked location30)
    (checked location31)
    (checked location32)
    (checked location33)
))
)
